<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>StlThumbConfig</AssemblyName>
    <RootNamespace>StlThumbConfig</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <SelfContained>false</SelfContained>
  </PropertyGroup>
</Project>
